# Generated by Django 5.0.14 on 2025-11-24 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("document_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=50,
                    ),
                ),
                ("documents_processed", models.IntegerField(default=0)),
                ("tasks_extracted", models.IntegerField(default=0)),
                ("cost_items_extracted", models.IntegerField(default=0)),
                ("chunks_created", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipeline_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_name",
                    models.CharField(
                        help_text="Description of the cost item", max_length=500
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of the item",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., t, m3, m2)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "unit_price_yen",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price in Japanese Yen",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost_yen",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost in Japanese Yen",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("foreign", "Foreign Cost"),
                            ("local", "Local Cost"),
                            ("other", "Other"),
                        ],
                        help_text="Type of cost (foreign/local)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Cost category or section",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_items",
                        to="pipeline.document",
                    ),
                ),
            ],
            options={
                "db_table": "cost_items",
                "ordering": ["-total_cost_yen"],
                "indexes": [
                    models.Index(
                        fields=["cost_type"], name="cost_items_cost_ty_49eb29_idx"
                    ),
                    models.Index(
                        fields=["total_cost_yen"], name="cost_items_total_c_c98321_idx"
                    ),
                    models.Index(
                        fields=["category"], name="cost_items_categor_28b0c3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chunk_id",
                    models.CharField(
                        help_text="Unique identifier matching ChromaDB",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The text content of this chunk"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Position of chunk in document"),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Source page number if applicable",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata stored as JSON"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="pipeline.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["chunk_id"], name="document_ch_chunk_i_a03216_idx"
                    ),
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="document_ch_documen_15f3c0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_id",
                    models.IntegerField(help_text="Unique task ID from the document"),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name/description of the task", max_length=500
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        help_text="Duration in days",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateField(help_text="Task start date")),
                ("finish_date", models.DateField(help_text="Task finish date")),
                (
                    "predecessor",
                    models.CharField(
                        blank=True,
                        help_text="Predecessor task IDs",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resource_names",
                    models.TextField(
                        blank=True,
                        help_text="Resources assigned to the task",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="pipeline.document",
                    ),
                ),
            ],
            options={
                "db_table": "project_tasks",
                "ordering": ["task_id"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="project_tas_task_id_1aae89_idx"
                    ),
                    models.Index(
                        fields=["start_date", "finish_date"],
                        name="project_tas_start_d_f42394_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_id",
                    models.CharField(
                        help_text="Unique rule identifier (e.g., Q1, Q2)", max_length=50
                    ),
                ),
                (
                    "rule_summary",
                    models.TextField(help_text="Concise summary of the rule"),
                ),
                (
                    "measurement_basis",
                    models.CharField(
                        blank=True,
                        help_text="Key measurement principle",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True, help_text="Complete rule text", null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="pipeline.document",
                    ),
                ),
            ],
            options={
                "db_table": "regulatory_rules",
                "ordering": ["rule_id"],
                "indexes": [
                    models.Index(
                        fields=["rule_id"], name="regulatory__rule_id_4471a6_idx"
                    )
                ],
            },
        ),
    ]
