# Generated by Django 5.0.14 on 2025-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="finish_date",
            field=models.DateField(blank=True, help_text="Task finish date", null=True),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="start_date",
            field=models.DateField(blank=True, help_text="Task start date", null=True),
        ),
    ]
